-- Con SYS en la CDB:
-- CONN / AS SYSDBA

-- 1) PDB correcta
ALTER SESSION SET CONTAINER = XEPDB1;
SHOW CON_NAME;

-- 2) Usuario de la app (si ya existe, solo UNLOCK)
-- Cambia la clave si lo necesitas y pon la misma en tu config.php
BEGIN
  EXECUTE IMMEDIATE q'[ALTER USER MONITOR ACCOUNT UNLOCK]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -01918 THEN
    EXECUTE IMMEDIATE q'[CREATE USER MONITOR IDENTIFIED BY "root" QUOTA UNLIMITED ON USERS]';
  ELSE
    RAISE;
  END IF;
END;
/

-- 3) Privilegios mínimos para crear vistas/procedimientos y consultar vistas de diccionario
GRANT CREATE SESSION TO MONITOR;
GRANT CREATE VIEW TO MONITOR;
GRANT CREATE TABLE TO MONITOR;
GRANT CREATE PROCEDURE TO MONITOR;

-- Rol de catálogo (simplifica grants a DBA_* y V_$*)
GRANT SELECT_CATALOG_ROLE TO MONITOR;
GRANT SELECT ANY DICTIONARY TO MONITOR;

-- Grants granulares útiles (por si la política es restrictiva)
GRANT SELECT ON SYS.V_$SYSMETRIC             TO MONITOR;
GRANT SELECT ON SYS.V_$SYSMETRIC_HISTORY     TO MONITOR;
GRANT SELECT ON SYS.V_$SESSION               TO MONITOR;
GRANT SELECT ON SYS.GV_$SESSION              TO MONITOR;
GRANT SELECT ON SYS.V_$SQL                   TO MONITOR;
GRANT SELECT ON SYS.V_$SQLAREA               TO MONITOR;
GRANT SELECT ON SYS.V_$SQLSTATS              TO MONITOR;
GRANT SELECT ON SYS.V_$TABLESPACE            TO MONITOR;
GRANT SELECT ON SYS.V_$DATAFILE              TO MONITOR;
GRANT EXECUTE ON DBMS_UTILITY TO MONITOR;
GRANT SELECT ON SYS.V_$OSSTAT           TO MONITOR;
GRANT SELECT ON SYS.V_$SYS_TIME_MODEL   TO MONITOR;
GRANT SELECT ON SYS.V_$PGASTAT          TO MONITOR;
GRANT SELECT ON SYS.V_$SGA_DYNAMIC_COMPONENTS TO MONITOR;
GRANT SELECT ON SYS.DBA_OBJECTS              TO MONITOR;
GRANT SELECT ON SYS.DBA_TABLESPACES          TO MONITOR;
GRANT SELECT ON SYS.DBA_DATA_FILES           TO MONITOR;
GRANT SELECT ON SYS.DBA_FREE_SPACE           TO MONITOR;

-- Backups vía controlfile (en XE están disponibles)
GRANT SELECT ON SYS.V_$BACKUP_SET            TO MONITOR;
GRANT SELECT ON SYS.V_$BACKUP_PIECE          TO MONITOR;

-- Paquetes necesarios para tus acciones
GRANT EXECUTE ON DBMS_STATS                  TO MONITOR;
GRANT EXECUTE ON UTL_RECOMP                  TO MONITOR;
GRANT EXECUTE ON DBMS_UTILITY TO MONITOR;


-- (Opcional) Perfil más tolerante mientras pruebas (evita re-bloqueos por intentos fallidos)
-- ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
